### ISSUE TITLE
Help Wanted: gui.py "Unable to find image 'strokect:latest' locally

### ISSUE THREAD

**Issue by SimonKato** [albertclerigues/stroke-core-ct-segmentation#1]
Hello, 
I am trying to use the model provided "isles18" to create inference from the testing data of ISLES2018 data. 
I have installed the pre-reqs: python, tkinter, and nvidia-docker2. 
I get the following issue when I press start Inference:
![docker](https://user-images.githubusercontent.com/38088338/99193994-8f4a3380-274a-11eb-9c64-f8dcd2796d19.JPG)

As far as data storage, I currently have the data stored in an unrelated folder not called /DATA/ISLES and have the clone of this repository in /home/user/stroke-core-ct-segmentation. I have tried putting the dataset in /stroke-core-ct-segmentation/storage/dataset/ and have gotten the same issue. I have also tried every location of where to put the isles18_testing.txt : inside ./storage/dataset, inside ./storage/dataset/testing, ./storage and nothing has worked.

Can any clarification of how to run the inference, or deal with the current issue be given please. 
Thank You

**Comment by albertclerigues** [comment]
Hi SimonKato, 
It seems the main issue is that it cannot find the docker image, either because it was not built correctly or because there is a permission error. The `gui.py` should take care of building the `strokect:latest`, so could you check the output of `docker ps`? 
If the image is not there you could manually build it by running `docker build --tag=strokect .` on the directory that contains the Dockerfile. If it says you don't have permission, you might have to add your user to the docker group.

In any case, first test that you can launch the docker manually (without using sudo) with this command: `docker run -it --ipc=host --runtime=nvidia strokect`. It will give errors since the storage is not mounted, but if it does launch then try again with the `gui.py`

**Comment by SimonKato** [comment]
Hi Albert,
To begin, I have checked and you are correct the issue is that the docker image is not being built at all. I realized this after I ran ```docker ps``` and saw that there are no images.
![docker_ps](https://user-images.githubusercontent.com/38088338/100951114-e6d2f800-34db-11eb-85e8-22fbda499105.JPG)

I tried to build the docker image using ```docker build --tag=strokect```
I have not changed anything in the docker file, but it is throwing me the following error:
![docker_build](https://user-images.githubusercontent.com/38088338/100951127-ef2b3300-34db-11eb-8233-770ce224df09.JPG)

This error appears whether I use sudo or not. This error also appears if I just try to build the docker image with ```docker build -tag .```

Lastly, I have checked ```grep docker /etc/group``` and I can confirm I am in the docker group.

I don't have any suspicions as to what might be happening, should I reach out to Soichi Hayashi?

**Comment by SimonKato** [comment]
Hi Albert,

I wanted to inform you that I found the solution to the issue this post was about. The issue concerned itself with the link to the miniconda.sh download, namely, that link downloads an empty installer.

Changing the link on line 68:  ```https://repo.continuum.io/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh```to ```https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh``` fixed this issue.

Moreover, on line 104 the graphviz install did not work but can be found on anaconda.org to be ```conda install -c asmeurer graphviz```
